version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - q
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - q
    env_file:
      - .env

  app:
    container_name: app
    build:
      context: .
    image: registry.digitalocean.com/ghoststead/q@sha256:9883e430b0b4e99024f2d39dacd0337858cf49dd3546afb11b07586fa989e0be
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      - q
    env_file:
      - .env
    depends_on:
      - mongo

networks:
  q:
    name: q